---
title: "Project 4"
author: "LeTicia Cancel"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

test one file of ham or spam
```{r}
#install.packages("readtext")
#install.packages("Rtools")
#install.packages("textreadr")
#install.packages("tidyverse")
#library(tidyverse)
#library(textreadr)
#library(readtext)
#?readtext

#create a list of all file names within the ham directory
file1 <- list.files(path = "ham", pattern = "[^.]*$", full.names = TRUE)
#file1

#rename all files in ham directory with a .txt extension 
newfiles <- gsub("[^.]*$", "txt", file1)
file.rename(file1, newfiles)
#file1

#new list of renamed files
renamed.list <- list.files(path = "ham", pattern = "[^.]*$", full.names = TRUE)
#renamed.list

#read the plain text files in the directory
#readChar(file1,file.info(file1)$size)
item1 <- print(renamed.list[1])
#item1

#read the text in just the first file in the list
#readChar(item1,file.info(item1)$size)

#length of renamed list
#length(renamed.list)


#open file connection and read files
#con <- file(path, open = "rt", raw = TRUE)

#con2 <- url(path, open = "rt")
#text <- readLines(con, skipNul = TRUE)
#text2 <- readLines(con2, skipNul = TRUE)
#text2
#text
#?file
#?list

#loop to read each of the list items
ham.list <- list()



for(x in 1:length(renamed.list)){
  ham.data.file <- renamed.list[x]
  ham.data <- readChar(ham.data.file,file.info(ham.data.file)$size)
  #ham.list <- list(ham.data)
  #if(x == 1){
    #add first list item
   # ham.list <- list(ham.data)
  #}
  #else{
    #append the list
   # ham.list[[x]] <- ham.data
  #}
  
  #?tibble
  
  if(x==1){
     ham.list <- list(ham.data)
    #x
  }
  else{
    ham.list <- list(ham.list, ham.data)
    #x
  }
  #tmp <- list(ham.data,file.info(ham.data)$size)
  #ham.list[[ham.data]] <- tmp 
}

x
ham.data

str(ham.data)

str(ham.list)

ham.list


#ham.list[300]
```

